### ISSUE TITLE
Window 10 users

### ISSUE THREAD

**Issue by louisc32578** [njh/sonoff-ota-flash-cli#11]
Can you direct me to anyone that may have addressed Window in DIY Sononff Mini R2

**Comment by njh** [comment]
No, I am not aware of anyone using Windows 10 with my script.
I don't have access to Windows, so I am not able to test.

Although the main reason I wrote to script is because there is a Windows tool available from Sonoff:
https://github.com/itead/Sonoff_Devices_DIY_Tools/tree/master/tool

But nothing for Mac / Linux.

If you need help, you could try contacting Sonoff Support.

**Comment by smoke007** [comment]
@louisc32578 I used the script on both Win10 and Win11 to flash my Sonoff Mini R2 boards.  I updated the [readme with directions](https://github.com/smoke007/sonoff-ota-flash-cli/tree/f5c46c3374d1036229d801462edb6fb6cece4c67) and submitted a [pull request to update it](https://github.com/njh/sonoff-ota-flash-cli/pull/17).
